
# dotpath=/Volumes/DataHD/astro_work/repos/dotfiles/zsh
dotpath=~/.zsh
# dotpath=$0:A:h

source $dotpath/checks.zsh
source $dotpath/colors.zsh
source $dotpath/setopt.zsh
source $dotpath/exports.zsh
source $dotpath/prompt.zsh
source $dotpath/completion.zsh
source $dotpath/aliases.zsh
source $dotpath/functions.zsh
source $dotpath/history.zsh
if [[ $IS_MAC -eq 1 ]]; then
    source `brew --prefix`/etc/profile.d/z.sh
fi
