dotpath=~/.zsh
# dotpath=$0:A:h

source $dotpath/checks.zsh
source $dotpath/colors.zsh
source $dotpath/setopt.zsh
source $dotpath/exports.zsh

# source $dotpath/prompt.zsh
autoload -U promptinit && promptinit
PURE_PROMPT_SYMBOL='%#'
prompt pure

source $dotpath/completion.zsh
source $dotpath/aliases.zsh
source $dotpath/functions.zsh
source $dotpath/history.zsh
if [[ $IS_MAC -eq 1 ]]; then
    source `brew --prefix`/etc/profile.d/z.sh
fi
if [[ -e $dotpath/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]]; then
    source $dotpath/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi
